// Code generated by "livefun codegen"; DO NOT EDIT.

package main

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var opsProcessed = promauto.NewCounter(prometheus.CounterOpts{
	Name: "myapp_processed_ops_total",
})

var mySecondMetric = promauto.NewGauge(prometheus.GaugeOpts{
	Name: "myapp_processed_ops_total_second",
})
